### ISSUE TITLE
Failed to resolve entry for package "@bobthered/tailwindcss-palette-generator"

### ISSUE THREAD

**Issue by wukaipeng-dev** [bobthered/tailwindcss-palette-generator#4]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/68799055/203981305-9b9225d6-0e10-4cb0-aa10-d42ee5cf855a.png">

**Comment by bobthered** [comment]
I pushed a patch ( [3.1.1](https://www.npmjs.com/package/@bobthered/tailwindcss-palette-generator) ) that should resolve this.
