### ISSUE TITLE
Cannot find module '@bobthered/tailwindcss-palette-generator'

### ISSUE THREAD

**Issue by jhgeluk** [bobthered/tailwindcss-palette-generator#7]
Hello,

I really like your package, but I'm having trouble importing it in my project using typescript. This seems to be broken since the latest version [3.2.2](https://www.npmjs.com/package/@bobthered/tailwindcss-palette-generator/v/3.2.2)

When trying to ES6 import statement: `import {tailwindcssPaletteGenerator} from '@bobthered/tailwindcss-palette-generator';
`

And when trying the CommonJS import statement: `const {tailwindcssPaletteGenerator} = require('@bobthered/tailwindcss-palette-generator');`

I get this error:
`Module not found: Error: Package path . is not exported from package /Users/redacted/redacted/project/node_modules/@bobthered/tailwindcss-palette-generator (see exports field in /Users/redacted/redacted/project/node_modules/@bobthered/tailwindcss-palette-generator/package.json)`

**Comment by bobthered** [comment]
Thanks @jhgeluk for this.  I converted this project over to a [Sveltekit Package](https://kit.svelte.dev/docs/packaging) and it looks like I needed to add the `main` key as well as the `require` key to the `exports.`  

If you update the package to the latest version [3.2.3](https://www.npmjs.com/package/@bobthered/tailwindcss-palette-generator/v/3.2.3) it should work.  I tested with ES6 import and CommonJS import.  Let me know if it still isn't working.
